name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Store Public IP
        run: bash store-public-ip.sh

      - name: SSH into VM and Run Container
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_PUBLIC_IP }} << 'EOF'
            docker run -d -p 8080:8080 my-nodejs-app
          EOF
