name: Azure Deployment with Service Principal

on:
  push:
    branches: [master]

permissions:
  contents: read  # Only needs read access to your code

env:
  TF_IN_AUTOMATION: true
  RESOURCE_GROUP_NAME: "github-actions-rg"
  VM_NAME: "deployment-vm"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login with Service Principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # JSON format
          enable-AzPSSession: false  # Faster login
          environment: azurecloud

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

      - name: Get VM IP
        id: get-ip
        run: echo "VM_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      - name: Deploy Application
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.VM_IP }}
          username: azureuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo apt-get update -y
            sudo apt-get install -y docker.io
            sudo systemctl enable --now docker
            sudo docker run -d -p 8080:8080 --name app your-image
